### ISSUE TITLE
HTS Screening Concepts

### ISSUE THREAD

**Issue by andie23** [HISMalawi/BHT-EMR-API#191]
Based on the HTS requirement spec, the following concepts are needed to capture some screening values in HTS
- Hepatitis B Test Result
- DBS Specimen ID
- Recency Test
- Long-Term
- Recent
- Patient consents to recency test
- PEP
- Prep or infant NVP
- Last HIV test performed
- Is DBS Sample Collected
- Time since last taken medication
- Receny Test

**Comment by Skipper-116** [comment]
Are recency test and receny test the same?
